In [1]:
import numpy as np

In [6]:
arr=np.arange(1,11)

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
#get element 6

arr[6]

7

In [9]:
#get last element
arr[-1]

10

In [12]:
#get slice
arr[:5]

array([1, 2, 3, 4, 5])

In [13]:
#get the even
arr[1::2]

array([ 2,  4,  6,  8, 10])

In [20]:
#get the boolean array
bool_arr= arr%2==0

In [21]:
bool_arr

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [22]:
arr[bool_arr]

array([ 2,  4,  6,  8, 10])

In [23]:
#get the even efficient method

arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [24]:
#get the odds

arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [16]:
#get the no greater than 5
arr[arr>5]

array([ 6,  7,  8,  9, 10])

Broadcasting :

In [25]:
arr[:5]=100

In [26]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [27]:
arr=np.arange(1,11)

In [28]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
sliced_array=arr[:5]

In [43]:
sliced_array[:]=400

In [44]:
sliced_array

array([400, 400, 400, 400, 400])

In [45]:
arr

array([400, 400, 400, 400, 400,   6,   7,   8,   9,  10])

In [47]:
arr=np.arange(1,11)

In [50]:
#copy the elements of arr into sliced_array upto the mentiomed index
sliced_arr=arr[:5].copy()

In [51]:
sliced_arr[:]=400

In [52]:
sliced_arr

array([400, 400, 400, 400, 400])

In [53]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2D array indexing or matrix indexing:

In [61]:
random_array=np.random.randint(1,50,(6,3))

In [62]:
random_array

array([[43, 38, 38],
       [14,  7, 13],
       [18, 36,  7],
       [41, 13, 31],
       [44, 15, 30],
       [34, 12, 41]])

In [65]:
#grab the 1st row:

random_array[0]

array([43, 38, 38])

In [66]:
#grab 1st 4 rows:
random_array[:4]

array([[43, 38, 38],
       [14,  7, 13],
       [18, 36,  7],
       [41, 13, 31]])

In [67]:
random_array[1:3,1:]

array([[ 7, 13],
       [36,  7]])

In [68]:
#grab a single element

random_array[4,1]

15