In [1]:
import numpy as np

In [2]:
list1=[1,2,3,4,5,6,7]


In [3]:
np.array(list1)

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#returns an array of 1 dimension between two ranges
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#returns an array of 1 dimension between two ranges .third argument is stepsize
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
#returns a array of n*1 dimension with all zeroes
np.zeros(3)

array([0., 0., 0.])

In [9]:
#returns an array of m*n dimension with all zeroes.
#It takes the dimensions as a touple
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
#returns an array of n*1 dimension with values 1
np.ones(3)

array([1., 1., 1.])

In [12]:
#returns an array of m*n dimension with values 1
#It takes the dimensions as a touple

np.ones((3,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

Linespace func:

In [13]:
#np.linspace(start,end,no_of_digits_are_to_be_placed_in_range)

np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [14]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

## Identity matrix

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Creating random arrays

In [18]:
# returns an array of 1*N dimension of random numbers
np.random.rand(5)

array([0.17141268, 0.82379452, 0.22245612, 0.38960075, 0.65494145])

In [19]:
# returns an array of M*M dimension of random numbers
np.random.rand(5,5)

array([[0.6091053 , 0.70808772, 0.20883251, 0.69186687, 0.17074241],
       [0.09006895, 0.41384618, 0.82107842, 0.43055481, 0.14461217],
       [0.78092341, 0.87264714, 0.36835866, 0.95472778, 0.77972373],
       [0.49082666, 0.65976522, 0.39485678, 0.84047903, 0.62045951],
       [0.52124056, 0.84829608, 0.42448481, 0.96174618, 0.28982972]])

In [20]:
# returns an array of M*N dimension of random numbers
np.random.rand(3,5)

array([[0.88304992, 0.94780438, 0.73635077, 0.20934523, 0.73265809],
       [0.93399377, 0.79450341, 0.20487335, 0.0807453 , 0.13923807],
       [0.01865391, 0.22726833, 0.84401665, 0.90283736, 0.05363628]])

In [21]:
#returns an array of M*N dimension of random numbers in standard normal distribution
np.random.randn(3,2)

array([[-0.0393718 , -1.97150026],
       [-0.12945591,  0.39128185],
       [-0.49489008,  0.3342287 ]])

In [22]:
#get a random integer between two range

np.random.randint(1,100)

86

In [23]:
#get multiple random integers say 10 integers between two range
#returns an array of n*1 dimension 

np.random.randint(1,100,10)

array([59,  4, 26, 63, 55, 39, 23, 91,  4, 28])

In [24]:
#get multiple random integers say 10 integers between two range
#returns an array of m*n dimension 
#It takes the dimension argument as a touple

np.random.randint(1,100,(10,2))

array([[26, 74],
       [19, 32],
       [25, 36],
       [52,  4],
       [91, 23],
       [17, 15],
       [21, 28],
       [86, 58],
       [46, 53],
       [ 2, 63]])

## some important methods in numpy arrays :

In [25]:
arr=np.arange(0,25)

In [26]:
#returns 1 dimension array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
#get a random array of 1 dimension
rand_array=np.random.randint(1,100,10)

In [28]:
rand_array

array([59, 54, 94, 63, 16, 25, 15, 62, 98, 96])

reshape() method :

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Max() Min():

In [30]:
#returns the maximum element in random array
rand_array.max()

98

In [31]:
#returns the index of max element in rndom array
rand_array.argmax()

8

In [32]:
#returns the minimum element in random array

rand_array.min()

15

In [33]:
#returns the index of min element in rndom array

rand_array.argmin()

6

In [34]:
rand_array_reshaped=rand_array.reshape(5,2)

In [35]:
rand_array_reshaped

array([[59, 54],
       [94, 63],
       [16, 25],
       [15, 62],
       [98, 96]])

In [36]:
#returns the maximum element in random array
rand_array_reshaped.max()

98

In [37]:
#returns the index of max element in rndom array

rand_array_reshaped.argmax()

8

In [38]:
# dimension of a array
rand_array.shape

(10,)

In [39]:
rand_array_reshaped.shape

(5, 2)

In [40]:
#get the datatype of an array
arr.dtype

dtype('int64')